spring:
  application:
    name: complete-project
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    session:
      persistent: false
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: adikaritharuka@gmail.com
    password: fcypgwmoykupbmin
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

mail:
  enabled: true

cinebook:
  mail:
    from: adikaritharuka@gmail.com